import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar"; //import ang navbar compoent para naay header ang whole site
import Sidebar from "./components/Sidebar"; //import ang sidebar component para naay sidebar ang whole site

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clense",
  description: "Generated by create next app and i modify so tha tican create a clense website",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <Sidebar />
        <main className="ml-64 pt-16">
          {children}
        </main>
      </body>
    </html>
  );
}
